[FSM]
name = "GameBoard"

[WAIT_FOR_ROLL]
events = ["DICE_ROLL"]

[PLAYER_MOVE]
events = ["PIP_SELECTED", "DICE_CLICKED"]

[MOVE_CONFIRM]
events = ["CONFIRMED_MOVE", "UNDO_MOVE"]

[GAME_OVER]
events = []
